config/routes.rb
Rails.application.routes.draw do
  resources :postulations
  resources :requests do
    member do
      patch :rate
    end
  end
  devise_for :users, path: "users", controllers: { sessions: "users/sessions" }

  resources :publications, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resource :profile, only: [ :show, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "publications#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  mount_uploader :picture, PictureUploader
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :picture, presence: true
  belongs_to :user
  has_many :requests

  def average_rating
    return 0 if requests.empty?

    total_rating = requests.where.not(rating: nil).sum(:rating)
    count = requests.where.not(rating: nil).count
    total_rating.to_f / count
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]

  # GET /publications or /publications.json
  def index
    # @publications = Publication.all
    if params[:search]
      @publications = Publication.joins(:user).where("lower(publications.name) LIKE ? OR lower(users.username) LIKE ?", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")
    else
      @publications = Publication.all
    end
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @average_rating = @publication.average_rating
  end
  
  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = current_user.publications.build(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy!

    respond_to do |format|
      format.html { redirect_to publications_path, status: :see_other, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.expect(publication: [ :name, :description, :picture, :price ])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> impiden que la publicación sea creada:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <div>
      <%= form.label :Nombre, style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div>
      <%= form.label :Descripción, style: "display: block" %>
      <%= form.textarea :description, class: "form-control" %>
    </div>

    <div>
      <%= form.label :Precio, style: "display: block" %>
      <%= form.number_field :price, class: "form-control" %>
    </div>


    <div>
      <%= form.label :Imagen, style: "display: block" %>
      <%= form.file_field :picture, class: "form-control-file" %>
    </div>

    <br><div>
      <%= form.submit "Guardar", class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div class="publicacion">
  <div class="texto">
    <p>
      <strong>Título:</strong>
      <%= publication.name %>
    </p>

    <p>
      <strong>Publicado por:</strong> <%= publication.user.username %>
    </p>

    <p>
      <strong>Descripción:</strong>
      <%= publication.description %>
    </p>
    
    <p>
      <strong>Precio:</strong>
      <%= publication.price %>
    </p>
  </div>

  <div class="imagen">
    <%= image_tag(publication.picture_url, width: 300) if publication.picture? %>
  </div>
</div>

app/views/publications/edit.html.erb
<% content_for :title, "Editing publication" %>

<h1>Editar Publicación</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Cancelar", @publication, class:"btn btn-secondary" %>
</div>

app/views/publications/index.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">ARTLINK</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Haz tus ideas realidad!</p>
  </div>
</div>

<p style="color: green"><%= notice %></p>

<% content_for :title, "Publications" %>

<div>
  <%= form_tag publications_path, method: :get, class: "form-inline d-flex" do %>
    <%= text_field_tag :search, params[:search], placeholder: "Buscar...", class: "form-control flex-grow-1" %>
    <%= submit_tag "Buscar", class: "btn btn-primary" %>
  <% end %>
</div>
<div class="service-container">
  <h3>Servicios</h3>
  <% @publications.each do |publication| %>
    <div class="service-item">
      <div class="service-text">
        <p><strong>Autor:</strong> <%= publication.user.username %></p>
        <p><strong>Título:</strong> <%= publication.name %></p>
        <p><strong>Precio:</strong> <%= publication.price %></p>
        <p>
          <%= link_to "Ver", publication, class:"btn btn-secondary" %>
        </p>
      </div>
      <div class="service-image">
        <%= image_tag(publication.picture_url, width: 300, height: 300) if publication.picture? %>
      </div>
    </div>
  <% end %>
</div>

app/views/publications/new.html.erb
<% content_for :title, "New publication" %>
<br>
<h1>Nueva publicación</h1>
<%= render "form", publication: @publication %>
<div>
  <%= link_to "Volver a Inicio", root_path, class:"btn btn-secondary" %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<div class="buttons-container">
  <% if current_user.id == @publication.user_id %>
    <%= link_to "Editar publicación", edit_publication_path(@publication), class:"btn btn-primary" %> 
    <%= button_to "Eliminar publicación", @publication, method: :delete, class:"btn btn-danger" %>
    <%= link_to "Regresar", profile_path, class:"btn btn-secondary" %>
  <%end%>
  <% if current_user.id != @publication.user_id %>
    <%= link_to "Regresar a inicio", root_path, class:"btn btn-secondary" %>
    <%= link_to "Solicitar servicio", new_request_path(publication_id: @publication.id), class:"btn btn-secondary" %>
  <%end%>
</div>

<p>
  <strong>Calificación Promedio:</strong>
  <div id="average-rating" data-score="<%= @average_rating %>"></div>
</p>

<script>
  $(document).ready(function() {
    $('#average-rating').raty({
      path: 'https://cdnjs.cloudflare.com/ajax/libs/raty/2.7.1/images',
      readOnly: true,
      score: function() {
        return $(this).data('score');
      }
    });
  });
</script>