config/routes.rb
Rails.application.routes.draw do
  resources :postulations
  resources :requests do
    member do
      patch :rate
    end
  end
  devise_for :users, path: "users", controllers: { sessions: "users/sessions" }

  resources :publications, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resource :profile, only: [ :show, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "publications#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/postulation.rb
class Postulation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: :sender_id
end

app/controllers/postulations_controller.rb
class PostulationsController < ApplicationController
  before_action :set_postulation, only: %i[ show edit update destroy ]

  # GET /postulations or /postulations.json
  def index
    # @postulations = Postulation.all
    @postulation_received = Postulation.where(receiver_id: 0)
    @postulation_sent = Postulation.where(sender_id: current_user.id)
  end

  # GET /postulations/1 or /postulations/1.json
  def show
  end

  # GET /postulations/new
  def new
    # Redirigir si el usuario ya tiene una postulación
    if current_user.sent_postulation.present?
      redirect_to postulation_path(current_user.sent_postulation), alert: "You have already submitted a postulation"
    else
      @postulation = Postulation.new(sender_id: current_user.id)
    end
  end

  # GET /postulations/1/edit
  def edit
  end

  # POST /postulations or /postulations.json
  def create
    if current_user.sent_postulation.present?
      redirect_to postulation_path(current_user.sent_postulation), alert: "You have already submitted a postulation."
    else
      @postulation = Postulation.new(postulation_params)
      respond_to do |format|
        if @postulation.save
          format.html { redirect_to @postulation, notice: "Postulation was successfully created." }
          format.json { render :show, status: :created, location: @postulation }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @postulation.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /postulations/1 or /postulations/1.json
  def update
    respond_to do |format|
      if @postulation.update(postulation_params)
        if @postulation.status == "Aceptado"
          @postulation.sender.update(access: 2)
        end
        format.html { redirect_to @postulation, notice: "Postulation was successfully updated." }
        format.json { render :show, status: :ok, location: @postulation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postulations/1 or /postulations/1.json
  def destroy
    @postulation.destroy!

    respond_to do |format|
      format.html { redirect_to postulations_path, status: :see_other, notice: "Postulation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postulation
      @postulation = Postulation.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def postulation_params
      params.expect(postulation: [ :title, :content, :portfolio, :sender_id, :receiver_id, :status, :username ])
    end
end

app/helpers/postulations_helper.rb
module PostulationsHelper
end

app/views/postulations/_form.html.erb
<%= form_with(model: postulation) do |form| %>
  <% if postulation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(postulation.errors.count, "error") %> impiden que la postulación sea creada:</h2>

      <ul>
        <% postulation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div>
    <%= form.hidden_field :sender_id %>
    <%= form.hidden_field :receiver_id %>
  </div>

<div class="form">
  <div>
    <%= form.label :Titulo, style: "display: block" %>
    <%= form.text_field :title, placeholder: "Titulo de la postulación", class: "form-control" %>
  </div>

  <div>
    <%= form.label :Descripción, style: "display: block" %>
    <%= form.textarea :content, placeholder: "Cuentanos por qué quieres ser un artista en nuestra plataforma", class: "form-control" %>
  </div>
  <div>
    <%= form.label :Usuario, style: "display: block" %>
    <%= form.text_field :username, placeholder: "Tu nombre de usuario", class: "form-control" %>
  </div>
  <div>
    <%= form.label :URL_Portafolio, style: "display: block" %>
    <%= form.text_field :portfolio, placeholder: "Coloca un URL a tu portafolio", class: "form-control" %>
  </div>

  <div>
     <%= form.submit "Aceptar", class:"btn btn-success" %>
  </div>
</div>
<% end %>

app/views/postulations/_postulation.html.erb
<div class="solicitud">
  <div class="texto">
    <p>
      <strong>Status:</strong>
      <%= postulation.status %>
    </p>
    <p>
      <strong>Asunto:</strong>
      <%= postulation.title %>
    </p>

    <p>
      <strong>Contenido:</strong>
      <%= postulation.content %>
    </p>

    <p>
      <strong>Portafolio:</strong>
      <%= postulation.portfolio %>
    </p>

    <p>
      <strong>Usuario:</strong>
      <%= postulation.username %>
    </p>
  </div>
</div>

app/views/postulations/edit.html.erb
<% content_for :title, "Editing postulations" %>

<h1>Aceptar o rechazar</h1>
 
<div>
<%= render @postulation %>
</div>
<%= form_with(model: @postulation) do |form| %>
  <div class="buttons-container">
    <strong>STATUS</strong>
    <%= form.select :status, ["Aceptado","Rechazado"], { class: 'form-control' } %>
    <br>
      <%= form.submit "Guardar", class:"btn btn-success" %>
  </div>
<%end%>

<br>

<div class="buttons-container">
  <%= link_to "Regresar a postulaciones", postulations_path, class:"btn btn-secondary"%>
</div>

app/views/postulations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Postulations" %>

<% if current_user.access == 0 %> 
  <h1>Bandeja de Postulaciones</h1> 
  <div id="requests"> 
    <h2>Recibidas</h2>
    <% @postulation_received.each do |postulation| %>
      <div class="postulations_received">
        <%= render postulation %> 
        <p>
          <%= link_to "Ver postulación", edit_postulation_path(postulation), class:"btn btn-secondary" %>
        </p>
      </div>
    <% end %>  
  </div>
<% end %>  

<% if current_user.access == 1 %> 
  <div id="requests">
    <h2>Mi postulación</h2>
      <% if @postulation_sent.any? %>
        <% @postulation_sent.each do |postulation| %>
          <div class="postulations_sent">
            <%= render postulation %> 
            <p>
              <%= link_to "Ver Postulación", postulation , class:"btn btn-secondary" %>
              
            </p>
          </div>
        <% end %>  
    <% else %>
      <p>Aún no te postulas, hazlo aquí:</p>
      <%= link_to "Postulate", new_postulation_path, class:"btn btn-primary edit-btn" %>
    <% end %>
  </div>
<% end %>  

app/views/postulations/new.html.erb
<% content_for :title, "New postulation" %>

<h1>Postulate como artista</h1>

<%= render "form", postulation: @postulation %>

<br>

<div>
  <%= link_to "Cancelar", publications_path, class:"btn btn-secondary" %>
</div>

app/views/postulations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @postulation %>

<div>
  <p>
    <%= link_to "Volver", profile_path, class:"btn btn-secondary" %>
    <% if current_user.access == 1 %>
      <%= button_to "Cancelar Postulación", @postulation, method: :delete, class:"btn btn-danger" %>
    <% end %>
  </p>
</div>