config/routes.rb
Rails.application.routes.draw do
  resources :postulations
  resources :requests do
    member do
      patch :rate
    end
  end
  devise_for :users, path: "users", controllers: { sessions: "users/sessions" }

  resources :publications, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resource :profile, only: [ :show, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "publications#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  belongs_to :receiver, class_name: "User", foreign_key: :receiver_id
  belongs_to :publication
  mount_uploader :picture, PictureRequestUploader
  validates :title, presence: true
  validates :description, presence: true
  validates :contact, presence: true
  validates :picture, presence: true
  validates :status, presence: true
  validates :rating, inclusion: { in: 1..5 }, allow_nil: true

  after_save :update_publication_rating, if: :saved_change_to_rating?

  private

  def update_publication_rating
    Rails.logger.info "Updating publication rating for publication ID: #{publication.id}"
    publication.average_rating
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy rate ]

  # GET /requests or /requests.json
  def index
    # @requests = Request.all
    @request_received = Request.where(receiver_id: current_user.id)
    @request_sent = Request.where(sender_id: current_user.id)
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    publication = Publication.find params[:publication_id]
    @request = Request.new(receiver_id: publication.user_id, sender_id: current_user.id, publication_id: publication.id)
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy!

    respond_to do |format|
      format.html { redirect_to requests_path, status: :see_other, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def rate
    if @request.update(rating: params[:request][:rating])
      redirect_to @request, notice: "Request was successfully rated."
    else
      render :show, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.expect(request: [ :title, :description, :contact, :picture, :sender_id, :receiver_id, :publication_id, :status, :rating ])
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request.errors.count, "error") %> impiden que la solicitud sea creada:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form">
  <div>
    <%= form.hidden_field :sender_id %>
    <%= form.hidden_field :receiver_id %>
    <%= form.hidden_field :publication_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact, class: "form-control" %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture, class: "form-control-file" %>
  </div>

  <div>
     <%= form.submit "Aceptar", class:"btn btn-success" %>
  </div>
</div>
<% end %>

app/views/requests/_request.html.erb
<div class="solicitud">
  <div class="imagen">
    <p>
      <%= image_tag(request.picture_url, width: 300) if request.picture? %>
    </p>
  </div>

  <div class="texto">
    <p>
      <strong>Status:</strong>
      <%= request.status %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= request.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= request.description %>
    </p>

    <p>
      <strong>Contact:</strong>
      <%= request.contact %>
    </p>
  </div>
</div>

app/views/requests/edit.html.erb
<% content_for :title, "Editing request" %>

<h1>Aceptar, rechazar o finalizar</h1>

<%# <%= render "form", request: @request %> 
<div>
<%= render @request %>
</div>
<%= form_with(model: @request) do |form| %>
  <div class="buttons-container">
    <strong>STATUS</strong>
    <%= form.select :status, ["Aceptado","Rechazado","Finalizado"], { class: 'form-control' } %>
    <br>
     <%= form.submit "Guardar", class:"btn btn-success" %>
  </div>
<%end%>

<br>

<div class="buttons-container">
  <%= link_to "Regresar a Solicitudes", requests_path, class:"btn btn-secondary"%>
</div>

app/views/requests/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Requests" %>

<h1>Bandeja de Solicitudes</h1>
<% if current_user.access == 2 %>    
  <div id="requests"> 
    <h2>Recibidas</h2>
    <% @request_received.each do |request| %>
      <div class="requests_received">
        <%= render request %> 
        <p>
          <%= link_to "Ver solicitud", edit_request_path(request), class:"btn btn-secondary" %>
        </p>
      </div>
    <% end %>  
  </div>
<% end %>  
<div id="requests">
  <h2>Enviadas</h2>
  <% @request_sent.each do |request| %>
    <div class="requests_sent">
      <%= render request %> 
      <p>
        <%= link_to "Ver solicitud", request , class:"btn btn-secondary" %>
      </p>
    </div>
  <% end %>  
</div>

app/views/requests/new.html.erb
<% content_for :title, "New request" %>

<h1>Solicitar Servicio</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Cancelar", publication_path(@request.publication_id), class:"btn btn-secondary" %>
</div>

app/views/requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @request %>

<div class="buttons-container">
  <%= link_to "Regresar a Solicitudes", requests_path, class:"btn btn-secondary" %>
  
  <% if current_user.id == @request.sender_id %>
    <%= button_to "Cancelar Solicitud", @request, method: :delete, class:"btn btn-danger" %>
  <% end %>
</div>

<% if @request.status == 'Finalizado' && @request.rating.nil? && current_user.id == @request.sender_id %>
  <%= form_with model: @request, url: rate_request_path(@request), method: :patch do |form| %>
    <div class="field">
      <%= form.label :rating %>
      <%= form.number_field :rating %>
      <div id="star-rating"></div>
      <%= form.hidden_field :rating, id: "rating-input" %>
    </div>
    <div class="actions">
      <%= form.submit "Rate" %>
    </div>
  <% end %>
<% end %>

<script>
  $(document).ready(function() {
    $('#star-rating').raty({
      path: 'https://cdnjs.cloudflare.com/ajax/libs/raty/2.7.1/images',
      scoreName: 'request[rating]',
      click: function(score, evt) {
        $('#rating-input').val(score);
      }
    });
  });
</script>