config/routes.rb
Rails.application.routes.draw do
  resources :postulations
  resources :requests do
    member do
      patch :rate
    end
  end
  devise_for :users, path: "users", controllers: { sessions: "users/sessions" }

  resources :publications, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resource :profile, only: [ :show, :edit, :update ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "publications#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Artlink 2 0" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/raty/2.7.1/jquery.raty.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raty/2.7.1/jquery.raty.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= publications_path %>">Artlink</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if controller.controller_name != 'registrations' %>
              <% if controller.controller_name != 'sessions'%>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(publications_path) %>" href="<%= publications_path %>">Inicio</a>
                </li>
                <% if current_user.access == 2 %> 
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(publications_path) %>" href="<%= new_publication_path %>">Nueva publicación</a>
                </li>
                <%end%>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(requests_path) %>" href="<%= requests_path %>">Solicitudes</a>
                </li>  
                <% if current_user.access == 1 %> 
                  <li class="nav-item">
                    <a class="nav-link <%= 'active' if current_page?(postulations_path) %>" href="<%= new_postulation_path %>">Postulate</a>
                  </li> 
                <%end%>
                <% if current_user.access == 0 %>                     
                  <li class="nav-item">
                    <a class="nav-link <%= 'active' if current_page?(postulations_path) %>" href="<%= postulations_path %>">Postulaciones</a>
                  </li> 
                <%end%>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(profile_path) %>" href="<%= profile_path %>">Perfil</a>
                </li>    
              <%end%>
              <%end%>
              <p class="navbar-text float-right">
                <% if user_signed_in? %>
                  <strong>|</strong>
                  <%= link_to "Ajustes", edit_user_registration_path, class: "navbar-link" %> 
                  <%= link_to "Cerrar sesión", destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-link"  %>
                <% else %>
                  <% if controller.controller_name != 'registrations' %>
                    <%= link_to "Registrarse", new_user_registration_path, class: "navbar-link"  %> 
                  <%end%>
                  <% if controller.controller_name != 'sessions' %>
                    <%= link_to "Iniciar sesión", new_user_session_path, class: "navbar-link"  %>
                  <%end%>
                <% end %>
              </p>
            </ul>
          </div>
        </div>
    </nav>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <footer class="mt-5 text-center">
    <div class="container">
      Artlink <%= Time.now.year %>
    </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>